### ISSUE TITLE
GraphQL to Typescript

### ISSUE THREAD

**Issue by tusharmath** [ritz078/transform#13]
Probably use — https://github.com/avantcredit/gql2ts

**Comment by ritz078** [comment]
https://transform.now.sh/graphql-to-typescript

**Comment by tusharmath** [comment]
This is great! Will give it a shot.

**Comment by tusharmath** [comment]
I am not able to edit the query field. Is there a way for you to fetch the schema using the introspection query from a URL instead of the dev copy pasting it? Probably have text box for entering a URL?

**Comment by ritz078** [comment]
Can you try now to edit the query field ?

**Comment by tusharmath** [comment]
Nope, the text area is awfully small. Plus it has this large element cover it
<img width="1915" alt="screen shot 2017-08-31 at 1 49 04 pm" src="https://user-images.githubusercontent.com/194482/29913591-3382e436-8e53-11e7-9bf5-ee27072798dc.png">
 —
 `#__next > div > div > div.content > div > div.content-wrapper > div.section.left.split` 


<img width="1915" alt="screen shot 2017-08-31 at 1 47 10 pm" src="https://user-images.githubusercontent.com/194482/29913489-fd68d78e-8e52-11e7-8a4e-511b55a813ef.png">

**Comment by ritz078** [comment]
I think it should be fixed now as I have replaced ace editor with codemirror.

**Comment by tusharmath** [comment]
@ritz078 Sorry for the late response, I have been a bit busy. 
Unfortunately its still not working, the left pane isn't scrollable :(

**Comment by ritz078** [comment]
I saw that on some browser. But its not happening on my browser. @cg-cnu Can you reproduce this on your machine ?

**Comment by cg-cnu** [comment]
Yes, its broken on my machine too.. chrome 55  on linux
![image](https://user-images.githubusercontent.com/2767425/30023896-034924da-918f-11e7-9379-83548d73efa5.png)

**Comment by ritz078** [comment]
@cg-cnu Can you look into this ? Should me a minor CSS issue.

**Comment by cg-cnu** [comment]
Sure.. am on it :slightly_smiling_face:
